create type "public"."blog_post_status" as enum ('PENDING', 'RELEASED');

drop policy "Enable read access for all users" on "public"."categories";

drop policy "Enable read access for all users" on "public"."labels";

drop policy "Enable read access for all users" on "public"."maps";

drop policy "Enable read access for all users" on "public"."points";

create table "public"."i18n" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now(),
    "long_text" text,
    "short_text" character varying,
    "local_id" uuid,
    "junction_i18n_id" uuid
);


alter table "public"."i18n" enable row level security;

create table "public"."junction_i18n" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."junction_i18n" enable row level security;

create table "public"."levels" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "name" character varying not null,
    "value" smallint not null,
    "map_id" bigint not null
);


alter table "public"."levels" enable row level security;

create table "public"."locales" (
    "id" uuid not null default uuid_generate_v4(),
    "name" character varying(255) not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "value" character varying not null default ''::character varying
);


alter table "public"."locales" enable row level security;

create table "public"."rel_tags_categories" (
    "category_id" bigint not null,
    "tag_id" bigint not null
);


alter table "public"."rel_tags_categories" enable row level security;

create table "public"."resources" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "name" character varying not null default ''::character varying,
    "path" character varying not null default ''::character varying,
    "content_id" uuid
);


alter table "public"."resources" enable row level security;

create table "public"."sections" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "name" character varying not null default ''::character varying,
    "level_id" bigint not null,
    "map_id" bigint not null
);


alter table "public"."sections" enable row level security;

create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone not null default now(),
    "name" character varying not null default ''::character varying,
    "content_id" uuid,
    "updated_at" timestamp without time zone not null default now(),
    "resource_id" bigint
);


alter table "public"."tags" enable row level security;

alter table "public"."categories" drop column "tags";

alter table "public"."categories" add column "content_id" uuid;

alter table "public"."categories" add column "updated_at" timestamp without time zone not null default now();

alter table "public"."categories" alter column "color" set default '"#fff"'::character varying;

alter table "public"."categories" alter column "color" set not null;

alter table "public"."categories" alter column "created_at" set data type timestamp without time zone using "created_at"::timestamp without time zone;

alter table "public"."categories" alter column "name" set not null;

alter table "public"."labels" add column "content_id" uuid;

alter table "public"."labels" add column "name" character varying not null default ''::character varying;

alter table "public"."labels" add column "section_id" bigint;

alter table "public"."labels" add column "updated_at" timestamp without time zone not null default now();

alter table "public"."labels" alter column "color" set default '"#fff"'::character varying;

alter table "public"."labels" alter column "color" set not null;

alter table "public"."labels" alter column "created_at" set data type timestamp without time zone using "created_at"::timestamp without time zone;

alter table "public"."labels" alter column "position" set data type jsonb using "position"::jsonb;

alter table "public"."labels" alter column "rotation" set default '0'::smallint;

alter table "public"."labels" alter column "rotation" set not null;

alter table "public"."labels" alter column "rotation" set data type smallint using "rotation"::smallint;

alter table "public"."labels" alter column "size" set default '10'::smallint;

alter table "public"."labels" alter column "size" set not null;

alter table "public"."maps" add column "total_level" smallint not null default '1'::smallint;

alter table "public"."maps" add column "updated_at" timestamp without time zone not null default now();

alter table "public"."maps" alter column "created_at" set data type timestamp without time zone using "created_at"::timestamp without time zone;

alter table "public"."maps" alter column "in_progress" set default true;

alter table "public"."maps" alter column "map_conifg" set default '{    "zoom": -2,     "minZoom": -1,     "maxZoom": 3,     "padding": [600, 600],     "imageDimensions": [1172.03, 792.57]}'::json;

alter table "public"."maps" alter column "map_conifg" set not null;

alter table "public"."maps" alter column "name" set default ''::character varying;

alter table "public"."maps" alter column "name" set not null;

alter table "public"."points" drop column "category";

alter table "public"."points" drop column "resource";

alter table "public"."points" drop column "tag";

alter table "public"."points" add column "category_id" bigint;

alter table "public"."points" add column "content_id" uuid;

alter table "public"."points" add column "name" character varying not null default ''::character varying;

alter table "public"."points" add column "resource_id" bigint;

alter table "public"."points" add column "section_id" bigint;

alter table "public"."points" add column "tag_id" bigint;

alter table "public"."points" add column "updated_at" timestamp without time zone not null default now();

alter table "public"."points" alter column "created_at" set data type timestamp without time zone using "created_at"::timestamp without time zone;

alter table "public"."points" alter column "position" set data type jsonb using "position"::jsonb;

CREATE UNIQUE INDEX i18n_pkey ON public.i18n USING btree (id);

CREATE UNIQUE INDEX junction_i18n_pkey ON public.junction_i18n USING btree (id);

CREATE UNIQUE INDEX levels_pkey ON public.levels USING btree (id);

CREATE UNIQUE INDEX locales_pkey ON public.locales USING btree (id);

CREATE UNIQUE INDEX resources_pkey ON public.resources USING btree (id);

CREATE UNIQUE INDEX sections_pkey ON public.sections USING btree (id);

CREATE UNIQUE INDEX tags_categories_pkey ON public.rel_tags_categories USING btree (category_id, tag_id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."i18n" add constraint "i18n_pkey" PRIMARY KEY using index "i18n_pkey";

alter table "public"."junction_i18n" add constraint "junction_i18n_pkey" PRIMARY KEY using index "junction_i18n_pkey";

alter table "public"."levels" add constraint "levels_pkey" PRIMARY KEY using index "levels_pkey";

alter table "public"."locales" add constraint "locales_pkey" PRIMARY KEY using index "locales_pkey";

alter table "public"."rel_tags_categories" add constraint "tags_categories_pkey" PRIMARY KEY using index "tags_categories_pkey";

alter table "public"."resources" add constraint "resources_pkey" PRIMARY KEY using index "resources_pkey";

alter table "public"."sections" add constraint "sections_pkey" PRIMARY KEY using index "sections_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."categories" add constraint "categories_content_id_fkey" FOREIGN KEY (content_id) REFERENCES junction_i18n(id) ON DELETE SET NULL not valid;

alter table "public"."categories" validate constraint "categories_content_id_fkey";

alter table "public"."i18n" add constraint "i18n_junction_i18n_id_fkey" FOREIGN KEY (junction_i18n_id) REFERENCES junction_i18n(id) ON DELETE RESTRICT not valid;

alter table "public"."i18n" validate constraint "i18n_junction_i18n_id_fkey";

alter table "public"."i18n" add constraint "i18n_local_id_fkey" FOREIGN KEY (local_id) REFERENCES locales(id) ON DELETE RESTRICT not valid;

alter table "public"."i18n" validate constraint "i18n_local_id_fkey";

alter table "public"."labels" add constraint "labels_content_id_fkey" FOREIGN KEY (content_id) REFERENCES junction_i18n(id) ON DELETE SET NULL not valid;

alter table "public"."labels" validate constraint "labels_content_id_fkey";

alter table "public"."labels" add constraint "labels_section_id_fkey" FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE RESTRICT not valid;

alter table "public"."labels" validate constraint "labels_section_id_fkey";

alter table "public"."levels" add constraint "levels_map_id_fkey" FOREIGN KEY (map_id) REFERENCES maps(id) ON DELETE RESTRICT not valid;

alter table "public"."levels" validate constraint "levels_map_id_fkey";

alter table "public"."points" add constraint "points_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL not valid;

alter table "public"."points" validate constraint "points_category_id_fkey";

alter table "public"."points" add constraint "points_content_id_fkey" FOREIGN KEY (content_id) REFERENCES junction_i18n(id) ON DELETE SET NULL not valid;

alter table "public"."points" validate constraint "points_content_id_fkey";

alter table "public"."points" add constraint "points_resource_id_fkey" FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE SET NULL not valid;

alter table "public"."points" validate constraint "points_resource_id_fkey";

alter table "public"."points" add constraint "points_section_id_fkey" FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE RESTRICT not valid;

alter table "public"."points" validate constraint "points_section_id_fkey";

alter table "public"."points" add constraint "points_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE SET NULL not valid;

alter table "public"."points" validate constraint "points_tag_id_fkey";

alter table "public"."rel_tags_categories" add constraint "rel_tags_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."rel_tags_categories" validate constraint "rel_tags_categories_category_id_fkey";

alter table "public"."rel_tags_categories" add constraint "rel_tags_categories_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) not valid;

alter table "public"."rel_tags_categories" validate constraint "rel_tags_categories_tag_id_fkey";

alter table "public"."resources" add constraint "resources_content_id_fkey" FOREIGN KEY (content_id) REFERENCES junction_i18n(id) ON DELETE RESTRICT not valid;

alter table "public"."resources" validate constraint "resources_content_id_fkey";

alter table "public"."sections" add constraint "sections_level_id_fkey" FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE SET NULL not valid;

alter table "public"."sections" validate constraint "sections_level_id_fkey";

alter table "public"."sections" add constraint "sections_map_id_fkey" FOREIGN KEY (map_id) REFERENCES maps(id) ON DELETE SET NULL not valid;

alter table "public"."sections" validate constraint "sections_map_id_fkey";

alter table "public"."tags" add constraint "tags_content_id_fkey" FOREIGN KEY (content_id) REFERENCES junction_i18n(id) not valid;

alter table "public"."tags" validate constraint "tags_content_id_fkey";

alter table "public"."tags" add constraint "tags_resource_id_fkey" FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE SET DEFAULT not valid;

alter table "public"."tags" validate constraint "tags_resource_id_fkey";

create policy "Enable read access for all users"
on "public"."i18n"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."junction_i18n"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."levels"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."locales"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."rel_tags_categories"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."resources"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."sections"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."tags"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."categories"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."labels"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."maps"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."points"
as permissive
for select
to anon
using (true);



